# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '9.x'
  displayName: 'Install Node.js'

- task: CmdLine@2
  displayName: 'npm install'
  continueOnError: false 
  inputs:
          script: 'npm install'
          workingDirectory: '$(Build.SourcesDirectory)'

- task: CmdLine@2
  displayName: 'npm run build'
  continueOnError: false 
  inputs:
          script: 'npm build'
          workingDirectory: '$(Build.SourcesDirectory)'  

- task: CopyFiles@2
  displayName: "Copy files"
  inputs:
            SourceFolder: '$(Build.SourcesDirectory)'
            Contents: '**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              ArtifactName: 'Contentful'
              publishLocation: 'Container'