# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest
stages:
  - stage: Build
    displayName: Build
    jobs:
       - job: 
         displayName: Build, Run and Publish
         steps:
            - task: NodeTool@0
              inputs:
                versionSpec: '9.x'
              displayName: 'Install Node.js'

            - task: CmdLine@2
              displayName: 'npm install'
              continueOnError: false 
              inputs:
                      script: 'npm install'
                      workingDirectory: '$(Build.SourcesDirectory)'

            - task: CmdLine@2
              displayName: 'npm run build'
              continueOnError: false 
              inputs:
                      script: 'npm build'
                      workingDirectory: '$(Build.SourcesDirectory)'  

            - task: CopyFiles@2
              displayName: "Copy files"
              inputs:
                        SourceFolder: '$(Build.SourcesDirectory)'
                        Contents: '**'
                        TargetFolder: '$(Build.ArtifactStagingDirectory)'

            - task: ArchiveFiles@2
              inputs:
                      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
                      includeRootFolder: false
                      archiveType: 'zip'
                      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
                      replaceExistingArchive: true

            - task: PublishBuildArtifacts@1
              inputs:
                            PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
                            ArtifactName: 'Contentful'
                            publishLocation: 'Container'

       - job:
       - deployment: VMDeploy
         displayName: Deploy to VM
         environment: 
                name: CloudSigma
                resourceType: VirtualMachine
                tags: dev, web # only deploy to virtual machines with this tag
         strategy:
                runOnce:
                  deploy:   
                      steps:
                        - task: IISWebAppManagementOnMachineGroup@0
                          displayName: IISWebAppManage
                          inputs:
                            IISDeploymentType: 'IISWebsite'
                            ActionIISWebsite: 'CreateOrUpdateWebsite'
                            WebsiteName: 'Contenful'
                            WebsitePhysicalPath: 'C:\contentful\Deployment'
                            WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
                            AddBinding: true
                            Bindings: 'http/All Unassigned:80:'
                          
                        - task: IISWebAppDeploymentOnMachineGroup@0
                          displayName: IISWebAppDeploy
                          inputs:
                              WebSiteName: 'IISWebAppDeploy'
                              VirtualApplication: 'CloudSigma'
                              Package: '$(System.DefaultWorkingDirectory)\**\*.zip'
                              TakeAppOfflineFlag: true
                              XmlVariableSubstitution: true